

### Dictionaries of the number of X's in the middle of cannonical PH binding motif
### Dictionary is X(n)
### Key is CATH id, value is the motif

amino_acids = {"ALA": "A", "GLY": "G", "GLU": "E", "ARG": "R",
                "TRP": "W", "TYR": "Y", "SER": "S", "ASN": "N",
                "ASP": "D", "CYS": "C", "GLN": "Q", "HIS": "H",
                "ILE": "I", "LEU": "L", "LYS": "K", "MET": "M",
                "PHE": "F", "PRO": "P", "THR": "T", "VAL": "V"}

x1 = {"3ml4C01": "KWKSR"}

x2 = {"2x18E00": "KNWRPR",
"1eazA00": "KNWKRR",
"1p6sA00": "KTWRPR",
"1unqA00": "KTWRPR",
"2i5fA00": "KNWKVR",
"1x1gA00": "KNWKVR",
"1x05A00": "KNWKVR",
"1wi1A01": "KRWKKR",
"1fhwA00": "KTWKRR",
"1u29A00": "KTWKRR",
"1fgyA00": "KTWKRR",
"1faoA00": "KTWKTR",
"1v5uA00": "KPWKAR",
"4kvgB02": "KSWKRR",
"4hatB00": "KEWKER",
"5cllB00": "KEWKER",
"3ml4C01": "KKWKSR",
"4gn1C02": "KSWKKR",
"2dkpA01": "KLWKKR",
"3mpxA02": ["KNRRPR", "KDGKYR"]}

x3 = {"2x18E00": "KKNWRPR",
"4kvgB02": "KKSWKRR",
"4gn1C02": "KKSWKKR",
"4khbB01": "KEPGKCR",
"2pz1A03": "KPEQKQR"}
x4 = {"1x1gA00": "KRKNWKVR"}

x5 = {"1w1hD00": "KIQEVWRQR",
"1v89A00": "KMGWLKKQR",
"3voqA00": "KVSMIHRLR",
"4hatB00": "KDAKEWKER",
"1maiA00": "KSSSWRRER"}

x6 = {"1wi1A01": "KNVWKRWKKR",
"5l81B00": "KDHLRIFRPR",
"2ys3A00": "KDHLRIFRPR",
"2dhkA01": "KGPIRGWKSR",
"5d3xB00": "KWLDAIIRER"}

x7 = {"1v5uA00": "KGAFMKPWKAR",
"4gn1C02": "KDDGKKSWKKR",
"4kvgB02": "KEDGKKSWKRR",
"2crfA01": "KTSQSWVERGR"}

x8 = {"2i5fA00": "KQGHRRKNWKVR",
"1x05A00": "KQGHRRKNWKVR",
"1x1gA00": "KQGHKRKNWKVR",
"1eazA00": "KQGAVMKNWKRR",
"1v5uA00": "KKGAFMKPWKAR",
"1p6sA00": "KRGEYIKTWRPR",
"1unqA00": "KRGEYIKTWRPR",
"2pz1A03": "KQRWLKAFARER",
"5d3xB00": "KQKWLDAIIRER",
"3voqA00": "KSFKVSMIHRLR",
"1tqzA01": "KLDQPDWTGRLR"}

x9 = {"1w1hD00": "KWCRKIQEVWRQR",
"2x18E00": "KRGEYIKKNWRPR",
"4chjA00": "KNFMNLTFNQKVR",
"2dkpA01": "KQDSTGMKLWKKR"}

x10 = {"2yf0A01": "KNFRTVHFIVPRER",
"3au4A04": "KLMKAYISMIVKKR"}

x11 = {"4l6eA00": "KLYRWDRDVSQWKER",
"4hatB00": "KLFRFDKDAKEWKER",
"1xkeA00": "KLFRFDAEVSQWKER"}

x12 = {"2pz1A03": "KPEQKQRWLKAFARER",
"1p3rC00": "KGMAAAGRSQGQHKQR"}

x13 = {"2d9zA01": "KEGWMVHYTSRDNLRKR",
"2d9vA01": "KVGQECQDVQPPEGRSR"}

x14 = {"1p6sA00": "KEGWLHKRGEYIKTWRPR",
"1unqA00": "KEGWLHKRGEYIKTWRPR",
"1eazA00": "KAGYCVKQGAVMKNWKRR",
"2i5fA00": "KQGCLLKQGHRRKNWKVR",
"1x05A00": "KQGCLLKQGHRRKNWKVR",
"2i1jA03": "KRILALCMGNHELYMRRR",
"4yl8A03": "KRILALCMGNHELYMRRR",
"2d9wA01": "KQGFLYLQQQQTFGKKWR",
"1x1gA00": "KQGYLAKQGHKRKNWKVR",
"4chjA00": "KIDRPKNFMNLTFNQKVR"}

x15 = {"2x18E00": "KEGWVQKRGEYIKKNWRPR",
"4l6eA00": "KERAKLYRWDRDVSQWKER",
"3hk0B02": "KQYNAPTDHGLCIKPNKVR",
"1kz7C02": "KPQRHLFLHEKAVLFCKKR"}

x16 = {"2cofA00": "KSRWCSVRDNHLHFYQDRNR",
"1wi1A01": "KHSGYLWAIGKNVWKRWKKR",
"1foeC02": "KLVGSHRLSIYEEWDPFRFR"}

x17 = {"3syxA00": "KVPHQEENGCADFFIRGERLR",
"1foeC02": "KKLVGSHRLSIYEEWDPFRFR"}

x18 = {"1unqA00": "KTWRPRYFLLKNDGTFIGYKER",
"1foeC02": "KKKLVGSHRLSIYEEWDPFRFR"}

x19 = {"3tfmA02": "KQGWLHNNGGGSSTLSRRNWKKR",
"4hatB00": "KEWKERGTGDCKFLKNKKTNKVR"}

x20 = {"5d3xB00": "KWFVCMAKTAEEKQKWLDAIIRER",
"2vrwB02": "KWSHMFLLIEDQGAQGYELFFKTR",
"1foeC02": "KQKKKLVGSHRLSIYEEWDPFRFR"}

x21 = {"2vrwB02": "KKWSHMFLLIEDQGAQGYELFFKTR"}

x22 = {"5d3xB00": "KNKWFVCMAKTAEEKQKWLDAIIRER",
"1p3rC00": "KMSQDSMMKLKGMAAAGRSQGQHKQR",
"2lulA00": "KNNNNIMIKYHPKFWTDGSYQCCRQT"}

x23 = {"1x05A00": "KEEFRGVIIKQGCLLKQGHRRKNWKVR"}

x24 = {"2dhiA00": "KVHMPVDCINIRTGHECRDIQPPDGKPR",
"1unqA00": "KRGEYIKTWRPRYFLLKNDGTFIGYKER"}

x27 = {"1unqA00": "KERPQDVDQREAPLNNFSVAQCQLMKTERPR"}

x28 = {"5d3xB00": "KIHNTAKNKWFVCMAKTAEEKQKWLDAIIRER",
"2pz1A03": "KSQQRMFFLFDHQLIYCKKDLLRRDVLYYKGR",
"2kcjA00": "KVHSADNTRMELIIPGEQHFYMKAVNAAERQR"}

x29 = {"4yl8A03": "KAPDFVFYAPRLRINKRILALCMGNHELYMRRR",
"2i1jA03": "KAPDFVFFAPRVRVNKRILALCMGNHELYMRRR"}

x30 = {"5l81B00": "KLLVPGMSEIYLRCQDEQQYAQWMAACRLASKGR",
"1unqA00": "KEGWLHKRGEYIKTWRPRYFLLKNDGTFIGYKER",
"4yl8A03": "KKAPDFVFYAPRLRINKRILALCMGNHELYMRRR",
"2i1jA03": "KKAPDFVFFAPRVRVNKRILALCMGNHELYMRRR",
"1p6sA00": "KEGWLHKRGEYIKTWRPRYFLLKSDGSFIGYKER"}

x31 = {"1w1hD00": "KTFFVHTPNRTYYLMDPSGNAHKWCRKIQEVWRQR",
"1tqzA01": "KPDVSVYRIPPRASNRGYRASDWKLDQPDWTGRLR"}

x33 = {"2ys3A00": "KLLVPSPEGMSEIYLRCQDEQQYARWMAGCRLASKGR"}

x34 = {"1w1hD00": "KNFKTFFVHTPNRTYYLMDPSGNAHKWCRKIQEVWRQR",
"5l81B00": "KFCIKLLVPGMSEIYLRCQDEQQYAQWMAACRLASKGR",
"4yl8A03": "KPIDKKAPDFVFYAPRLRINKRILALCMGNHELYMRRR",
"2i1jA03": "KPIDKKAPDFVFFAPRVRVNKRILALCMGNHELYMRRR",
"2vrwB02": "KASVNLHSFQVRDKKWSHMFLLIEDQGAQGYELFFKTR",
"1kz7C02": "KLLQGSFSVWTDHKELARFKPQRHLFLHEKAVLFCKKR"}

x35 = {"2kcjA00": "KMAVCEIKVHSADNTRMELIIPGEQHFYMKAVNAAERQR"}

x37 = {"2ys3A00": "KFCIKLLVPSPEGMSEIYLRCQDEQQYARWMAGCRLASKGR"}

x38 = {"2i1jA03": "KFIIKPIDKKAPDFVFFAPRVRVNKRILALCMGNHELYMRRR",
"4yl8A03": "KFVIKPIDKKAPDFVFYAPRLRINKRILALCMGNHELYMRRR"}

x39 = {"2yf0A01": "KETWILHHHIASVEKLALTTSGCPLVIQCKNFRTVHFIVPRER",
"2kcjA00": "KGSIKMAVCEIKVHSADNTRMELIIPGEQHFYMKAVNAAERQR",
"4yl8A03": "KKFVIKPIDKKAPDFVFYAPRLRINKRILALCMGNHELYMRRR"}

x41 = {"1mkeA00": "KLLWEQELYNNFVYNSPRGYFHTFAGDTCQVALNFANEEEAKKFR"}

x42 = {"2kcjA00": "KGSKGSIKMAVCEIKVHSADNTRMELIIPGEQHFYMKAVNAAERQR"}

x43 = {"3f0wA00": "KAFSYICRDGTTRRWICHCFLALKDSGERLSHAVGCAFAACLERKQR"}

x44 = {"1mkeA00": "KDGKLLWEQELYNNFVYNSPRGYFHTFAGDTCQVALNFANEEEAKKFR",
"3zvrA03": "KGWLTINNIGIMSKEYWFVLTAENLSWYKDDEEKEKKYMLSVDNLKLR"}

x45 = {"4chjA00": "KEAFDNWMNRYEAGDTMEVLFPDGHRIECNLKIDRPKNFMNLTFNQKVR"}

x46 = {"1unqA00": "KTWRPRYFLLKNDGTFIGYKERPQDVDQREAPLNNFSVAQCQLMKTERPR"}


allxmotifs = [x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16,
x17, x18, x19, x20, x21, x22, x23, x24, x27, x28, x29, x30, x30, x31, x33,
x34, x35, x37, x38, x39, x41, x42, x43, x44, x45, x46]

# pdbs = []
# list_of_motifseqs = []

# for xn_motifs in allxmotifs:
#     for key in xn_motifs:
#         if key not in pdbs:
#             pdbs.append(key)

# print(pdbs)
# # print(len(pdbs))

pdbs = ['3ml4C01', '2x18E00', '1eazA00', '1p6sA00', '1unqA00', '2i5fA00',
        '1x1gA00', '1x05A00', '1wi1A01', '1fhwA00', '1u29A00', '1fgyA00',
        '1faoA00', '1v5uA00', '4kvgB02', '4hatB00', '5cllB00', '4gn1C02',
        '2dkpA01', '3mpxA02', '4khbB01', '2pz1A03', '1w1hD00', '1v89A00',
        '3voqA00', '1maiA00', '5l81B00', '2ys3A00', '2dhkA01', '5d3xB00',
        '2crfA01', '1tqzA01', '4chjA00', '2yf0A01', '3au4A04', '4l6eA00',
        '1xkeA00', '1p3rC00', '2d9zA01', '2d9vA01', '2i1jA03', '4yl8A03',
        '2d9wA01', '4l6eA00', '3hk0B02', '1kz7C02', '2cofA00', '1foeC02',
        '3syxA00', '3tfmA02', '2vrwB02', '2lulA00', '2dhiA00', '2kcjA00',
        '1mkeA00', '3f0wA00', '3zvrA03']


all_motifs = ['KWKSR', 'KNWRPR', 'KNWKRR', 'KTWRPR', 'KTWRPR', 'KNWKVR',
              'KNWKVR', 'KNWKVR', 'KRWKKR', 'KTWKRR', 'KTWKRR', 'KTWKRR',
              'KTWKTR', 'KPWKAR', 'KSWKRR', 'KEWKER', 'KEWKER', 'KKWKSR',
              'KSWKKR', 'KLWKKR', 'KNRRPR', 'KDGKYR', 'KKNWRPR', 'KKSWKRR',
              'KKSWKKR', 'KEPGKCR', 'KPEQKQR', 'KRKNWKVR', 'KIQEVWRQR',
              'KMGWLKKQR', 'KVSMIHRLR', 'KDAKEWKER', 'KSSSWRRER', 'KNVWKRWKKR',
              'KDHLRIFRPR', 'KDHLRIFRPR', 'KGPIRGWKSR', 'KWLDAIIRER',
              'KGAFMKPWKAR', 'KDDGKKSWKKR', 'KEDGKKSWKRR', 'KTSQSWVERGR',
              'KQGHRRKNWKVR', 'KQGHRRKNWKVR', 'KQGHKRKNWKVR', 'KQGAVMKNWKRR',
              'KKGAFMKPWKAR', 'KRGEYIKTWRPR', 'KRGEYIKTWRPR', 'KQRWLKAFARER',
              'KQKWLDAIIRER', 'KSFKVSMIHRLR', 'KLDQPDWTGRLR', 'KWCRKIQEVWRQR',
              'KRGEYIKKNWRPR', 'KNFMNLTFNQKVR', 'KQDSTGMKLWKKR',
              'KNFRTVHFIVPRER', 'KLMKAYISMIVKKR', 'KLYRWDRDVSQWKER',
              'KLFRFDKDAKEWKER', 'KLFRFDAEVSQWKER', 'KPEQKQRWLKAFARER',
              'KGMAAAGRSQGQHKQR', 'KEGWMVHYTSRDNLRKR', 'KVGQECQDVQPPEGRSR',
              'KEGWLHKRGEYIKTWRPR', 'KEGWLHKRGEYIKTWRPR', 'KAGYCVKQGAVMKNWKRR',
              'KQGCLLKQGHRRKNWKVR', 'KQGCLLKQGHRRKNWKVR', 'KRILALCMGNHELYMRRR',
              'KRILALCMGNHELYMRRR', 'KQGFLYLQQQQTFGKKWR', 'KQGYLAKQGHKRKNWKVR',
              'KIDRPKNFMNLTFNQKVR', 'KEGWVQKRGEYIKKNWRPR',
              'KERAKLYRWDRDVSQWKER', 'KQYNAPTDHGLCIKPNKVR',
              'KPQRHLFLHEKAVLFCKKR', 'KSRWCSVRDNHLHFYQDRNR',
              'KHSGYLWAIGKNVWKRWKKR', 'KLVGSHRLSIYEEWDPFRFR',
              'KVPHQEENGCADFFIRGERLR', 'KKLVGSHRLSIYEEWDPFRFR',
              'KTWRPRYFLLKNDGTFIGYKER', 'KKKLVGSHRLSIYEEWDPFRFR',
              'KQGWLHNNGGGSSTLSRRNWKKR', 'KEWKERGTGDCKFLKNKKTNKVR',
              'KWFVCMAKTAEEKQKWLDAIIRER', 'KWSHMFLLIEDQGAQGYELFFKTR',
              'KQKKKLVGSHRLSIYEEWDPFRFR', 'KKWSHMFLLIEDQGAQGYELFFKTR',
              'KNKWFVCMAKTAEEKQKWLDAIIRER', 'KMSQDSMMKLKGMAAAGRSQGQHKQR',
              'KNNNNIMIKYHPKFWTDGSYQCCRQT', 'KEEFRGVIIKQGCLLKQGHRRKNWKVR',
              'KVHMPVDCINIRTGHECRDIQPPDGKPR', 'KRGEYIKTWRPRYFLLKNDGTFIGYKER',
'KERPQDVDQREAPLNNFSVAQCQLMKTERPR',
'KIHNTAKNKWFVCMAKTAEEKQKWLDAIIRER', 'KSQQRMFFLFDHQLIYCKKDLLRRDVLYYKGR', 'KVHSADNTRMELIIPGEQHFYMKAVNAAERQR',
'KAPDFVFYAPRLRINKRILALCMGNHELYMRRR', 'KAPDFVFFAPRVRVNKRILALCMGNHELYMRRR',
'KLLVPGMSEIYLRCQDEQQYAQWMAACRLASKGR', 'KEGWLHKRGEYIKTWRPRYFLLKNDGTFIGYKER', 'KKAPDFVFYAPRLRINKRILALCMGNHELYMRRR', 'KKAPDFVFFAPRVRVNKRILALCMGNHELYMRRR', 'KEGWLHKRGEYIKTWRPRYFLLKSDGSFIGYKER',
'KLLVPGMSEIYLRCQDEQQYAQWMAACRLASKGR', 'KEGWLHKRGEYIKTWRPRYFLLKNDGTFIGYKER', 'KKAPDFVFYAPRLRINKRILALCMGNHELYMRRR', 'KKAPDFVFFAPRVRVNKRILALCMGNHELYMRRR', 'KEGWLHKRGEYIKTWRPRYFLLKSDGSFIGYKER',
'KTFFVHTPNRTYYLMDPSGNAHKWCRKIQEVWRQR', 'KPDVSVYRIPPRASNRGYRASDWKLDQPDWTGRLR',
'KLLVPSPEGMSEIYLRCQDEQQYARWMAGCRLASKGR',
'KNFKTFFVHTPNRTYYLMDPSGNAHKWCRKIQEVWRQR', 'KFCIKLLVPGMSEIYLRCQDEQQYAQWMAACRLASKGR', 'KPIDKKAPDFVFYAPRLRINKRILALCMGNHELYMRRR', 'KPIDKKAPDFVFFAPRVRVNKRILALCMGNHELYMRRR', 'KASVNLHSFQVRDKKWSHMFLLIEDQGAQGYELFFKTR', 'KLLQGSFSVWTDHKELARFKPQRHLFLHEKAVLFCKKR',
'KMAVCEIKVHSADNTRMELIIPGEQHFYMKAVNAAERQR',
'KFCIKLLVPSPEGMSEIYLRCQDEQQYARWMAGCRLASKGR',
'KFIIKPIDKKAPDFVFFAPRVRVNKRILALCMGNHELYMRRR', 'KFVIKPIDKKAPDFVFYAPRLRINKRILALCMGNHELYMRRR',
'KETWILHHHIASVEKLALTTSGCPLVIQCKNFRTVHFIVPRER', 'KGSIKMAVCEIKVHSADNTRMELIIPGEQHFYMKAVNAAERQR', 'KKFVIKPIDKKAPDFVFYAPRLRINKRILALCMGNHELYMRRR',
'KLLWEQELYNNFVYNSPRGYFHTFAGDTCQVALNFANEEEAKKFR',
'KGSKGSIKMAVCEIKVHSADNTRMELIIPGEQHFYMKAVNAAERQR',
'KAFSYICRDGTTRRWICHCFLALKDSGERLSHAVGCAFAACLERKQR',
'KDGKLLWEQELYNNFVYNSPRGYFHTFAGDTCQVALNFANEEEAKKFR', 'KGWLTINNIGIMSKEYWFVLTAENLSWYKDDEEKEKKYMLSVDNLKLR',
'KEAFDNWMNRYEAGDTMEVLFPDGHRIECNLKIDRPKNFMNLTFNQKVR',
'KTWRPRYFLLKNDGTFIGYKERPQDVDQREAPLNNFSVAQCQLMKTERPR']

# lpos_min2 = []
# spos_min2 = ""
# for seq in all_motifs:
#     lpos_min2.append(seq[-2])

# print(lpos_min2)
# spos_min2 = "".join(lpos_min2)
# print(spos_min2)


#138 motifs in total, with these AAs in their -2 position
pos_min2 = "SPRPPVVVKRRRTAREESKKPYPRKCQVQQLEEKPPSEAKRGVVVRAPPEELLQPVKEKEEEEQKSPPRVVRRWVVPEVKNKFLFEFKVETFTEQQVPEPEGQRRGERREGERREQLGQGRRTKQGRREQRFQQFLVP"
print(pos_min2.count("V"))

# A = 3
# G = 7
# E = 23
# R = 22
# W = 1
# Y = 1
# S = 4
# N = 1
# D = 0
# C = 1
# Q = 14
# H = 0
# I = 0
# L = 6
# K = 13
# M = 0
# F = 6
# P = 16
# T = 4
# V = 16
